#!/bin/bash

# experiment with multi-condition training, SIF + energy
python mytrain_inc.py --filter_sizes "1" --num_filters 100 --train_data "../train_data_multi_tensorflow_plus.mat" --test_data "../dev_data_multi_tensorflow_plus.mat" --out_dir 'runs/w_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "1" --num_filters 100 --train_data "../train_data_multi_tensorflow_plus.mat" --test_data "../test_data_tensorflow_plus.mat" --test_data_mix20 "../test_data_mix20_tensorflow_plus.mat" --test_data_mix10 "../test_data_mix10_tensorflow_plus.mat" --test_data_mix0 "../test_data_mix0_tensorflow_plus.mat" --out_dir 'runs/w_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "3" --num_filters 100 --train_data "../train_data_multi_tensorflow_plus.mat" --test_data "../dev_data_multi_tensorflow_plus.mat" --out_dir 'runs/w_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "3" --num_filters 100 --train_data "../train_data_multi_tensorflow_plus.mat" --test_data "../test_data_tensorflow_plus.mat" --test_data_mix20 "../test_data_mix20_tensorflow_plus.mat" --test_data_mix10 "../test_data_mix10_tensorflow_plus.mat" --test_data_mix0 "../test_data_mix0_tensorflow_plus.mat" --out_dir 'runs/w_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "5" --num_filters 100 --train_data "../train_data_multi_tensorflow_plus.mat" --test_data "../dev_data_multi_tensorflow_plus.mat" --out_dir 'runs/w_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "5" --num_filters 100 --train_data "../train_data_multi_tensorflow_plus.mat" --test_data "../test_data_tensorflow_plus.mat" --test_data_mix20 "../test_data_mix20_tensorflow_plus.mat" --test_data_mix10 "../test_data_mix10_tensorflow_plus.mat" --test_data_mix0 "../test_data_mix0_tensorflow_plus.mat" --out_dir 'runs/w_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "7" --num_filters 100 --train_data "../train_data_multi_tensorflow_plus.mat" --test_data "../dev_data_multi_tensorflow_plus.mat" --out_dir 'runs/w_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "7" --num_filters 100 --train_data "../train_data_multi_tensorflow_plus.mat" --test_data "../test_data_tensorflow_plus.mat" --test_data_mix20 "../test_data_mix20_tensorflow_plus.mat" --test_data_mix10 "../test_data_mix10_tensorflow_plus.mat" --test_data_mix0 "../test_data_mix0_tensorflow_plus.mat" --out_dir 'runs/w_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "9" --num_filters 100 --train_data "../train_data_multi_tensorflow_plus.mat" --test_data "../dev_data_multi_tensorflow_plus.mat" --out_dir 'runs/w_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "9" --num_filters 100 --train_data "../train_data_multi_tensorflow_plus.mat" --test_data "../test_data_tensorflow_plus.mat" --test_data_mix20 "../test_data_mix20_tensorflow_plus.mat" --test_data_mix10 "../test_data_mix10_tensorflow_plus.mat" --test_data_mix0 "../test_data_mix0_tensorflow_plus.mat" --out_dir 'runs/w_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "11" --num_filters 100 --train_data "../train_data_multi_tensorflow_plus.mat" --test_data "../dev_data_multi_tensorflow_plus.mat" --out_dir 'runs/w_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "11" --num_filters 100 --train_data "../train_data_multi_tensorflow_plus.mat" --test_data "../test_data_tensorflow_plus.mat" --test_data_mix20 "../test_data_mix20_tensorflow_plus.mat" --test_data_mix10 "../test_data_mix10_tensorflow_plus.mat" --test_data_mix0 "../test_data_mix0_tensorflow_plus.mat" --out_dir 'runs/w_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "13" --num_filters 100 --train_data "../train_data_multi_tensorflow_plus.mat" --test_data "../dev_data_multi_tensorflow_plus.mat" --out_dir 'runs/w_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "13" --num_filters 100 --train_data "../train_data_multi_tensorflow_plus.mat" --test_data "../test_data_tensorflow_plus.mat" --test_data_mix20 "../test_data_mix20_tensorflow_plus.mat" --test_data_mix10 "../test_data_mix10_tensorflow_plus.mat" --test_data_mix0 "../test_data_mix0_tensorflow_plus.mat" --out_dir 'runs/w_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "15" --num_filters 100 --train_data "../train_data_multi_tensorflow_plus.mat" --test_data "../dev_data_multi_tensorflow_plus.mat" --out_dir 'runs/w_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "15" --num_filters 100 --train_data "../train_data_multi_tensorflow_plus.mat" --test_data "../test_data_tensorflow_plus.mat" --test_data_mix20 "../test_data_mix20_tensorflow_plus.mat" --test_data_mix10 "../test_data_mix10_tensorflow_plus.mat" --test_data_mix0 "../test_data_mix0_tensorflow_plus.mat" --out_dir 'runs/w_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "17" --num_filters 100 --train_data "../train_data_multi_tensorflow_plus.mat" --test_data "../dev_data_multi_tensorflow_plus.mat" --out_dir 'runs/w_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "17" --num_filters 100 --train_data "../train_data_multi_tensorflow_plus.mat" --test_data "../test_data_tensorflow_plus.mat" --test_data_mix20 "../test_data_mix20_tensorflow_plus.mat" --test_data_mix10 "../test_data_mix10_tensorflow_plus.mat" --test_data_mix0 "../test_data_mix0_tensorflow_plus.mat" --out_dir 'runs/w_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "19" --num_filters 100 --train_data "../train_data_multi_tensorflow_plus.mat" --test_data "../dev_data_multi_tensorflow_plus.mat" --out_dir 'runs/w_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "19" --num_filters 100 --train_data "../train_data_multi_tensorflow_plus.mat" --test_data "../test_data_tensorflow_plus.mat" --test_data_mix20 "../test_data_mix20_tensorflow_plus.mat" --test_data_mix10 "../test_data_mix10_tensorflow_plus.mat" --test_data_mix0 "../test_data_mix0_tensorflow_plus.mat" --out_dir 'runs/w_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "21" --num_filters 100 --train_data "../train_data_multi_tensorflow_plus.mat" --test_data "../dev_data_multi_tensorflow_plus.mat" --out_dir 'runs/w_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "21" --num_filters 100 --train_data "../train_data_multi_tensorflow_plus.mat" --test_data "../test_data_tensorflow_plus.mat" --test_data_mix20 "../test_data_mix20_tensorflow_plus.mat" --test_data_mix10 "../test_data_mix10_tensorflow_plus.mat" --test_data_mix0 "../test_data_mix0_tensorflow_plus.mat" --out_dir 'runs/w_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "23" --num_filters 100 --train_data "../train_data_multi_tensorflow_plus.mat" --test_data "../dev_data_multi_tensorflow_plus.mat" --out_dir 'runs/w_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "23" --num_filters 100 --train_data "../train_data_multi_tensorflow_plus.mat" --test_data "../test_data_tensorflow_plus.mat" --test_data_mix20 "../test_data_mix20_tensorflow_plus.mat" --test_data_mix10 "../test_data_mix10_tensorflow_plus.mat" --test_data_mix0 "../test_data_mix0_tensorflow_plus.mat" --out_dir 'runs/w_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "25" --num_filters 100 --train_data "../train_data_multi_tensorflow_plus.mat" --test_data "../dev_data_multi_tensorflow_plus.mat" --out_dir 'runs/w_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "25" --num_filters 100 --train_data "../train_data_multi_tensorflow_plus.mat" --test_data "../test_data_tensorflow_plus.mat" --test_data_mix20 "../test_data_mix20_tensorflow_plus.mat" --test_data_mix10 "../test_data_mix10_tensorflow_plus.mat" --test_data_mix0 "../test_data_mix0_tensorflow_plus.mat" --out_dir 'runs/w_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "1,3,5,7,9,11,13,15,17,19,21,23,25" --num_filters 100 --train_data "../train_data_multi_tensorflow_plus.mat" --test_data "../dev_data_multi_tensorflow_plus.mat" --out_dir 'runs/w_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "1,3,5,7,9,11,13,15,17,19,21,23,25" --num_filters 100 --train_data "../train_data_multi_tensorflow_plus.mat" --test_data "../test_data_tensorflow_plus.mat" --test_data_mix20 "../test_data_mix20_tensorflow_plus.mat" --test_data_mix10 "../test_data_mix10_tensorflow_plus.mat" --test_data_mix0 "../test_data_mix0_tensorflow_plus.mat" --out_dir 'runs/w_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001

# experiment with multi-condition training, SIF
python mytrain_inc.py --filter_sizes "1" --num_filters 100 --train_data "../train_data_multi_tensorflow.mat" --test_data "../dev_data_multi_tensorflow.mat" --out_dir 'runs/wo_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "1" --num_filters 100 --train_data "../train_data_multi_tensorflow.mat" --test_data "../test_data_tensorflow.mat" --test_data_mix20 "../test_data_mix20_tensorflow.mat" --test_data_mix10 "../test_data_mix10_tensorflow.mat" --test_data_mix0 "../test_data_mix0_tensorflow.mat" --out_dir 'runs/wo_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "3" --num_filters 100 --train_data "../train_data_multi_tensorflow.mat" --test_data "../dev_data_multi_tensorflow.mat" --out_dir 'runs/wo_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "3" --num_filters 100 --train_data "../train_data_multi_tensorflow.mat" --test_data "../test_data_tensorflow.mat" --test_data_mix20 "../test_data_mix20_tensorflow.mat" --test_data_mix10 "../test_data_mix10_tensorflow.mat" --test_data_mix0 "../test_data_mix0_tensorflow.mat" --out_dir 'runs/wo_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "5" --num_filters 100 --train_data "../train_data_multi_tensorflow.mat" --test_data "../dev_data_multi_tensorflow.mat" --out_dir 'runs/wo_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "5" --num_filters 100 --train_data "../train_data_multi_tensorflow.mat" --test_data "../test_data_tensorflow.mat" --test_data_mix20 "../test_data_mix20_tensorflow.mat" --test_data_mix10 "../test_data_mix10_tensorflow.mat" --test_data_mix0 "../test_data_mix0_tensorflow.mat" --out_dir 'runs/wo_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "7" --num_filters 100 --train_data "../train_data_multi_tensorflow.mat" --test_data "../dev_data_multi_tensorflow.mat" --out_dir 'runs/wo_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "7" --num_filters 100 --train_data "../train_data_multi_tensorflow.mat" --test_data "../test_data_tensorflow.mat" --test_data_mix20 "../test_data_mix20_tensorflow.mat" --test_data_mix10 "../test_data_mix10_tensorflow.mat" --test_data_mix0 "../test_data_mix0_tensorflow.mat" --out_dir 'runs/wo_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "9" --num_filters 100 --train_data "../train_data_multi_tensorflow.mat" --test_data "../dev_data_multi_tensorflow.mat" --out_dir 'runs/wo_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "9" --num_filters 100 --train_data "../train_data_multi_tensorflow.mat" --test_data "../test_data_tensorflow.mat" --test_data_mix20 "../test_data_mix20_tensorflow.mat" --test_data_mix10 "../test_data_mix10_tensorflow.mat" --test_data_mix0 "../test_data_mix0_tensorflow.mat" --out_dir 'runs/wo_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "11" --num_filters 100 --train_data "../train_data_multi_tensorflow.mat" --test_data "../dev_data_multi_tensorflow.mat" --out_dir 'runs/wo_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "11" --num_filters 100 --train_data "../train_data_multi_tensorflow.mat" --test_data "../test_data_tensorflow.mat" --test_data_mix20 "../test_data_mix20_tensorflow.mat" --test_data_mix10 "../test_data_mix10_tensorflow.mat" --test_data_mix0 "../test_data_mix0_tensorflow.mat" --out_dir 'runs/wo_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "13" --num_filters 100 --train_data "../train_data_multi_tensorflow.mat" --test_data "../dev_data_multi_tensorflow.mat" --out_dir 'runs/wo_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "13" --num_filters 100 --train_data "../train_data_multi_tensorflow.mat" --test_data "../test_data_tensorflow.mat" --test_data_mix20 "../test_data_mix20_tensorflow.mat" --test_data_mix10 "../test_data_mix10_tensorflow.mat" --test_data_mix0 "../test_data_mix0_tensorflow.mat" --out_dir 'runs/wo_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "15" --num_filters 100 --train_data "../train_data_multi_tensorflow.mat" --test_data "../dev_data_multi_tensorflow.mat" --out_dir 'runs/wo_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "15" --num_filters 100 --train_data "../train_data_multi_tensorflow.mat" --test_data "../test_data_tensorflow.mat" --test_data_mix20 "../test_data_mix20_tensorflow.mat" --test_data_mix10 "../test_data_mix10_tensorflow.mat" --test_data_mix0 "../test_data_mix0_tensorflow.mat" --out_dir 'runs/wo_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "17" --num_filters 100 --train_data "../train_data_multi_tensorflow.mat" --test_data "../dev_data_multi_tensorflow.mat" --out_dir 'runs/wo_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "17" --num_filters 100 --train_data "../train_data_multi_tensorflow.mat" --test_data "../test_data_tensorflow.mat" --test_data_mix20 "../test_data_mix20_tensorflow.mat" --test_data_mix10 "../test_data_mix10_tensorflow.mat" --test_data_mix0 "../test_data_mix0_tensorflow.mat" --out_dir 'runs/wo_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "19" --num_filters 100 --train_data "../train_data_multi_tensorflow.mat" --test_data "../dev_data_multi_tensorflow.mat" --out_dir 'runs/wo_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "19" --num_filters 100 --train_data "../train_data_multi_tensorflow.mat" --test_data "../test_data_tensorflow.mat" --test_data_mix20 "../test_data_mix20_tensorflow.mat" --test_data_mix10 "../test_data_mix10_tensorflow.mat" --test_data_mix0 "../test_data_mix0_tensorflow.mat" --out_dir 'runs/wo_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "21" --num_filters 100 --train_data "../train_data_multi_tensorflow.mat" --test_data "../dev_data_multi_tensorflow.mat" --out_dir 'runs/wo_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "21" --num_filters 100 --train_data "../train_data_multi_tensorflow.mat" --test_data "../test_data_tensorflow.mat" --test_data_mix20 "../test_data_mix20_tensorflow.mat" --test_data_mix10 "../test_data_mix10_tensorflow.mat" --test_data_mix0 "../test_data_mix0_tensorflow.mat" --out_dir 'runs/wo_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "23" --num_filters 100 --train_data "../train_data_multi_tensorflow.mat" --test_data "../dev_data_multi_tensorflow.mat" --out_dir 'runs/wo_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "23" --num_filters 100 --train_data "../train_data_multi_tensorflow.mat" --test_data "../test_data_tensorflow.mat" --test_data_mix20 "../test_data_mix20_tensorflow.mat" --test_data_mix10 "../test_data_mix10_tensorflow.mat" --test_data_mix0 "../test_data_mix0_tensorflow.mat" --out_dir 'runs/wo_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "25" --num_filters 100 --train_data "../train_data_multi_tensorflow.mat" --test_data "../dev_data_multi_tensorflow.mat" --out_dir 'runs/wo_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "25" --num_filters 100 --train_data "../train_data_multi_tensorflow.mat" --test_data "../test_data_tensorflow.mat" --test_data_mix20 "../test_data_mix20_tensorflow.mat" --test_data_mix10 "../test_data_mix10_tensorflow.mat" --test_data_mix0 "../test_data_mix0_tensorflow.mat" --out_dir 'runs/wo_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "1,3,5,7,9,11,13,15,17,19,21,23,25" --num_filters 100 --train_data "../train_data_multi_tensorflow.mat" --test_data "../dev_data_multi_tensorflow.mat" --out_dir 'runs/wo_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "1,3,5,7,9,11,13,15,17,19,21,23,25" --num_filters 100 --train_data "../train_data_multi_tensorflow.mat" --test_data "../test_data_tensorflow.mat" --test_data_mix20 "../test_data_mix20_tensorflow.mat" --test_data_mix10 "../test_data_mix10_tensorflow.mat" --test_data_mix0 "../test_data_mix0_tensorflow.mat" --out_dir 'runs/wo_energy_multi/' --num_epochs 500 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001


# experiment with mismatched training, SIF + energy
python mytrain_inc.py --filter_sizes "1" --num_filters 100 --train_data "../train_data_tensorflow_plus.mat" --test_data "../dev_data_tensorflow_plus.mat" --out_dir 'runs/w_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "1" --num_filters 100 --train_data "../train_data_tensorflow_plus.mat" --test_data "../test_data_tensorflow_plus.mat" --test_data_mix20 "../test_data_mix20_tensorflow_plus.mat" --test_data_mix10 "../test_data_mix10_tensorflow_plus.mat" --test_data_mix0 "../test_data_mix0_tensorflow_plus.mat" --out_dir 'runs/w_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "3" --num_filters 100 --train_data "../train_data_tensorflow_plus.mat" --test_data "../dev_data_tensorflow_plus.mat" --out_dir 'runs/w_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "3" --num_filters 100 --train_data "../train_data_tensorflow_plus.mat" --test_data "../test_data_tensorflow_plus.mat" --test_data_mix20 "../test_data_mix20_tensorflow_plus.mat" --test_data_mix10 "../test_data_mix10_tensorflow_plus.mat" --test_data_mix0 "../test_data_mix0_tensorflow_plus.mat" --out_dir 'runs/w_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "5" --num_filters 100 --train_data "../train_data_tensorflow_plus.mat" --test_data "../dev_data_tensorflow_plus.mat" --out_dir 'runs/w_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "5" --num_filters 100 --train_data "../train_data_tensorflow_plus.mat" --test_data "../test_data_tensorflow_plus.mat" --test_data_mix20 "../test_data_mix20_tensorflow_plus.mat" --test_data_mix10 "../test_data_mix10_tensorflow_plus.mat" --test_data_mix0 "../test_data_mix0_tensorflow_plus.mat" --out_dir 'runs/w_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "7" --num_filters 100 --train_data "../train_data_tensorflow_plus.mat" --test_data "../dev_data_tensorflow_plus.mat" --out_dir 'runs/w_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "7" --num_filters 100 --train_data "../train_data_tensorflow_plus.mat" --test_data "../test_data_tensorflow_plus.mat" --test_data_mix20 "../test_data_mix20_tensorflow_plus.mat" --test_data_mix10 "../test_data_mix10_tensorflow_plus.mat" --test_data_mix0 "../test_data_mix0_tensorflow_plus.mat" --out_dir 'runs/w_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "9" --num_filters 100 --train_data "../train_data_tensorflow_plus.mat" --test_data "../dev_data_tensorflow_plus.mat" --out_dir 'runs/w_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "9" --num_filters 100 --train_data "../train_data_tensorflow_plus.mat" --test_data "../test_data_tensorflow_plus.mat" --test_data_mix20 "../test_data_mix20_tensorflow_plus.mat" --test_data_mix10 "../test_data_mix10_tensorflow_plus.mat" --test_data_mix0 "../test_data_mix0_tensorflow_plus.mat" --out_dir 'runs/w_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "11" --num_filters 100 --train_data "../train_data_tensorflow_plus.mat" --test_data "../dev_data_tensorflow_plus.mat" --out_dir 'runs/w_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "11" --num_filters 100 --train_data "../train_data_tensorflow_plus.mat" --test_data "../test_data_tensorflow_plus.mat" --test_data_mix20 "../test_data_mix20_tensorflow_plus.mat" --test_data_mix10 "../test_data_mix10_tensorflow_plus.mat" --test_data_mix0 "../test_data_mix0_tensorflow_plus.mat" --out_dir 'runs/w_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "13" --num_filters 100 --train_data "../train_data_tensorflow_plus.mat" --test_data "../dev_data_tensorflow_plus.mat" --out_dir 'runs/w_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "13" --num_filters 100 --train_data "../train_data_tensorflow_plus.mat" --test_data "../test_data_tensorflow_plus.mat" --test_data_mix20 "../test_data_mix20_tensorflow_plus.mat" --test_data_mix10 "../test_data_mix10_tensorflow_plus.mat" --test_data_mix0 "../test_data_mix0_tensorflow_plus.mat" --out_dir 'runs/w_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "15" --num_filters 100 --train_data "../train_data_tensorflow_plus.mat" --test_data "../dev_data_tensorflow_plus.mat" --out_dir 'runs/w_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "15" --num_filters 100 --train_data "../train_data_tensorflow_plus.mat" --test_data "../test_data_tensorflow_plus.mat" --test_data_mix20 "../test_data_mix20_tensorflow_plus.mat" --test_data_mix10 "../test_data_mix10_tensorflow_plus.mat" --test_data_mix0 "../test_data_mix0_tensorflow_plus.mat" --out_dir 'runs/w_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "17" --num_filters 100 --train_data "../train_data_tensorflow_plus.mat" --test_data "../dev_data_tensorflow_plus.mat" --out_dir 'runs/w_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "17" --num_filters 100 --train_data "../train_data_tensorflow_plus.mat" --test_data "../test_data_tensorflow_plus.mat" --test_data_mix20 "../test_data_mix20_tensorflow_plus.mat" --test_data_mix10 "../test_data_mix10_tensorflow_plus.mat" --test_data_mix0 "../test_data_mix0_tensorflow_plus.mat" --out_dir 'runs/w_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "19" --num_filters 100 --train_data "../train_data_tensorflow_plus.mat" --test_data "../dev_data_tensorflow_plus.mat" --out_dir 'runs/w_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "19" --num_filters 100 --train_data "../train_data_tensorflow_plus.mat" --test_data "../test_data_tensorflow_plus.mat" --test_data_mix20 "../test_data_mix20_tensorflow_plus.mat" --test_data_mix10 "../test_data_mix10_tensorflow_plus.mat" --test_data_mix0 "../test_data_mix0_tensorflow_plus.mat" --out_dir 'runs/w_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "21" --num_filters 100 --train_data "../train_data_tensorflow_plus.mat" --test_data "../dev_data_tensorflow_plus.mat" --out_dir 'runs/w_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "21" --num_filters 100 --train_data "../train_data_tensorflow_plus.mat" --test_data "../test_data_tensorflow_plus.mat" --test_data_mix20 "../test_data_mix20_tensorflow_plus.mat" --test_data_mix10 "../test_data_mix10_tensorflow_plus.mat" --test_data_mix0 "../test_data_mix0_tensorflow_plus.mat" --out_dir 'runs/w_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "23" --num_filters 100 --train_data "../train_data_tensorflow_plus.mat" --test_data "../dev_data_tensorflow_plus.mat" --out_dir 'runs/w_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "23" --num_filters 100 --train_data "../train_data_tensorflow_plus.mat" --test_data "../test_data_tensorflow_plus.mat" --test_data_mix20 "../test_data_mix20_tensorflow_plus.mat" --test_data_mix10 "../test_data_mix10_tensorflow_plus.mat" --test_data_mix0 "../test_data_mix0_tensorflow_plus.mat" --out_dir 'runs/w_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "25" --num_filters 100 --train_data "../train_data_tensorflow_plus.mat" --test_data "../dev_data_tensorflow_plus.mat" --out_dir 'runs/w_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "25" --num_filters 100 --train_data "../train_data_tensorflow_plus.mat" --test_data "../test_data_tensorflow_plus.mat" --test_data_mix20 "../test_data_mix20_tensorflow_plus.mat" --test_data_mix10 "../test_data_mix10_tensorflow_plus.mat" --test_data_mix0 "../test_data_mix0_tensorflow_plus.mat" --out_dir 'runs/w_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "1,3,5,7,9,11,13,15,17,19,21,23,25" --num_filters 100 --train_data "../train_data_tensorflow_plus.mat" --test_data "../dev_data_tensorflow_plus.mat" --out_dir 'runs/w_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "1,3,5,7,9,11,13,15,17,19,21,23,25" --num_filters 100 --train_data "../train_data_tensorflow_plus.mat" --test_data "../test_data_tensorflow_plus.mat" --test_data_mix20 "../test_data_mix20_tensorflow_plus.mat" --test_data_mix10 "../test_data_mix10_tensorflow_plus.mat" --test_data_mix0 "../test_data_mix0_tensorflow_plus.mat" --out_dir 'runs/w_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001

# experiment with mismatched training, SIF
python mytrain_inc.py --filter_sizes "1" --num_filters 100 --train_data "../train_data_tensorflow.mat" --test_data "../dev_data_tensorflow.mat" --out_dir 'runs/wo_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "1" --num_filters 100 --train_data "../train_data_tensorflow.mat" --test_data "../test_data_tensorflow.mat" --test_data_mix20 "../test_data_mix20_tensorflow.mat" --test_data_mix10 "../test_data_mix10_tensorflow.mat" --test_data_mix0 "../test_data_mix0_tensorflow.mat"  --out_dir 'runs/wo_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "3" --num_filters 100 --train_data "../train_data_tensorflow.mat" --test_data "../dev_data_tensorflow.mat" --out_dir 'runs/wo_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "3" --num_filters 100 --train_data "../train_data_tensorflow.mat" --test_data "../test_data_tensorflow.mat" --test_data_mix20 "../test_data_mix20_tensorflow.mat" --test_data_mix10 "../test_data_mix10_tensorflow.mat" --test_data_mix0 "../test_data_mix0_tensorflow.mat" --out_dir 'runs/wo_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "5" --num_filters 100 --train_data "../train_data_tensorflow.mat" --test_data "../dev_data_tensorflow.mat" --out_dir 'runs/wo_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "5" --num_filters 100 --train_data "../train_data_tensorflow.mat" --test_data "../test_data_tensorflow.mat" --test_data_mix20 "../test_data_mix20_tensorflow.mat" --test_data_mix10 "../test_data_mix10_tensorflow.mat" --test_data_mix0 "../test_data_mix0_tensorflow.mat" --out_dir 'runs/wo_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "7" --num_filters 100 --train_data "../train_data_tensorflow.mat" --test_data "../dev_data_tensorflow.mat" --out_dir 'runs/wo_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "7" --num_filters 100 --train_data "../train_data_tensorflow.mat" --test_data "../test_data_tensorflow.mat" --test_data_mix20 "../test_data_mix20_tensorflow.mat" --test_data_mix10 "../test_data_mix10_tensorflow.mat" --test_data_mix0 "../test_data_mix0_tensorflow.mat" --out_dir 'runs/wo_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "9" --num_filters 100 --train_data "../train_data_tensorflow.mat" --test_data "../dev_data_tensorflow.mat" --out_dir 'runs/wo_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "9" --num_filters 100 --train_data "../train_data_tensorflow.mat" --test_data "../test_data_tensorflow.mat" --test_data_mix20 "../test_data_mix20_tensorflow.mat" --test_data_mix10 "../test_data_mix10_tensorflow.mat" --test_data_mix0 "../test_data_mix0_tensorflow.mat" --out_dir 'runs/wo_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "11" --num_filters 100 --train_data "../train_data_tensorflow.mat" --test_data "../dev_data_tensorflow.mat" --out_dir 'runs/wo_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "11" --num_filters 100 --train_data "../train_data_tensorflow.mat" --test_data "../test_data_tensorflow.mat" --test_data_mix20 "../test_data_mix20_tensorflow.mat" --test_data_mix10 "../test_data_mix10_tensorflow.mat" --test_data_mix0 "../test_data_mix0_tensorflow.mat" --out_dir 'runs/wo_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "13" --num_filters 100 --train_data "../train_data_tensorflow.mat" --test_data "../dev_data_tensorflow.mat" --out_dir 'runs/wo_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "13" --num_filters 100 --train_data "../train_data_tensorflow.mat" --test_data "../test_data_tensorflow.mat" --test_data_mix20 "../test_data_mix20_tensorflow.mat" --test_data_mix10 "../test_data_mix10_tensorflow.mat" --test_data_mix0 "../test_data_mix0_tensorflow.mat" --out_dir 'runs/wo_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "15" --num_filters 100 --train_data "../train_data_tensorflow.mat" --test_data "../dev_data_tensorflow.mat" --out_dir 'runs/wo_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "15" --num_filters 100 --train_data "../train_data_tensorflow.mat" --test_data "../test_data_tensorflow.mat" --test_data_mix20 "../test_data_mix20_tensorflow.mat" --test_data_mix10 "../test_data_mix10_tensorflow.mat" --test_data_mix0 "../test_data_mix0_tensorflow.mat" --out_dir 'runs/wo_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "17" --num_filters 100 --train_data "../train_data_tensorflow.mat" --test_data "../dev_data_tensorflow.mat" --out_dir 'runs/wo_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "17" --num_filters 100 --train_data "../train_data_tensorflow.mat" --test_data "../test_data_tensorflow.mat" --test_data_mix20 "../test_data_mix20_tensorflow.mat" --test_data_mix10 "../test_data_mix10_tensorflow.mat" --test_data_mix0 "../test_data_mix0_tensorflow.mat" --out_dir 'runs/wo_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "19" --num_filters 100 --train_data "../train_data_tensorflow.mat" --test_data "../dev_data_tensorflow.mat" --out_dir 'runs/wo_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "19" --num_filters 100 --train_data "../train_data_tensorflow.mat" --test_data "../test_data_tensorflow.mat" --test_data_mix20 "../test_data_mix20_tensorflow.mat" --test_data_mix10 "../test_data_mix10_tensorflow.mat" --test_data_mix0 "../test_data_mix0_tensorflow.mat" --out_dir 'runs/wo_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "21" --num_filters 100 --train_data "../train_data_tensorflow.mat" --test_data "../dev_data_tensorflow.mat" --out_dir 'runs/wo_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "21" --num_filters 100 --train_data "../train_data_tensorflow.mat" --test_data "../test_data_tensorflow.mat" --test_data_mix20 "../test_data_mix20_tensorflow.mat" --test_data_mix10 "../test_data_mix10_tensorflow.mat" --test_data_mix0 "../test_data_mix0_tensorflow.mat" --out_dir 'runs/wo_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "23" --num_filters 100 --train_data "../train_data_tensorflow.mat" --test_data "../dev_data_tensorflow.mat" --out_dir 'runs/wo_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "23" --num_filters 100 --train_data "../train_data_tensorflow.mat" --test_data "../test_data_tensorflow.mat" --test_data_mix20 "../test_data_mix20_tensorflow.mat" --test_data_mix10 "../test_data_mix10_tensorflow.mat" --test_data_mix0 "../test_data_mix0_tensorflow.mat" --out_dir 'runs/wo_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001#
python mytrain_inc.py --filter_sizes "25" --num_filters 100 --train_data "../train_data_tensorflow.mat" --test_data "../dev_data_tensorflow.mat" --out_dir 'runs/wo_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "25" --num_filters 100 --train_data "../train_data_tensorflow.mat" --test_data "../test_data_tensorflow.mat" --test_data_mix20 "../test_data_mix20_tensorflow.mat" --test_data_mix10 "../test_data_mix10_tensorflow.mat" --test_data_mix0 "../test_data_mix0_tensorflow.mat" --out_dir 'runs/wo_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytrain_inc.py --filter_sizes "1,3,5,7,9,11,13,15,17,19,21,23,25" --num_filters 100 --train_data "../train_data_tensorflow.mat" --test_data "../dev_data_tensorflow.mat" --out_dir 'runs/wo_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001
python mytest.py --filter_sizes "1,3,5,7,9,11,13,15,17,19,21,23,25" --num_filters 100 --train_data "../train_data_tensorflow.mat" --test_data "../test_data_tensorflow.mat" --test_data_mix20 "../test_data_mix20_tensorflow.mat" --test_data_mix10 "../test_data_mix10_tensorflow.mat" --test_data_mix0 "../test_data_mix0_tensorflow.mat" --out_dir 'runs/wo_energy_mismatch/' --num_epochs 1000 --evaluate_every 50 --checkpoint_every 50 --batch_size 100 --l2_reg_lambda 0.0001




